<?php 
$body = '<!DOCTYPE html>';
$body .= '<html lang="es">';
$body .= '<meta charset="UTF-8">';
$body .= '<meta name="viewport" content="width=device-width,initial-scale=1">';
$body .= '<meta name="x-apple-disable-message-reformatting">';
$body .= '<title></title>	';
$body .= '<style>';
$body .= 'table, td, div, h1, p {font-family: Arial, sans-serif;}';
$body .= '</style>';
$body .= '</head>';
$body .= '<body style="margin:0;padding:0;">';
$body .= '<table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0;background:#ffffff;">';
$body .= '<tr>';
$body .= '<td align="center" style="padding:0;">';
$body .= '<table role="presentation" style="width:602px;border-collapse:collapse;border:1px solid #cccccc;border-spacing:0;text-align:left;">';
$body .= '<tr>';
$body .= '<td align="center" style="padding:40px 0 30px 0;background:#EEEEEE;">';
$body .= '<img src="http://fullvitec.com/web/assets/img/logo_fv.png" alt="" width="300" style="height:auto;display:block;" />';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="padding:36px 30px 42px 30px;">';
$body .= '<table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0;">';
$body .= '<tr>';
$body .= '<td colspan="2" style="padding:0 0 36px 0;color:#153643;">';
$body .= '<h1 style="font-size:24px;margin:0 0 20px 0;font-family:Arial,sans-serif;">Nueva Consulta</h1>';
$body .= '</td>';
$body .= '</tr>	';
$body .= '<tr>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;"><strong>Nombre:</strong></p></td>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;">'.$data->name.'</p></td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;"><strong>Email:</strong></p></td>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;">'.$data->email.'</p></td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;"><strong>Asunto:</strong></p></td>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;">'.$data->subject.'</p></td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;"><strong>Mensaje:</strong></p></td>';
$body .= '<td><p style="margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;">'.$data->message.'</p></td>';
$body .= '</tr>';
$body .= '</table>';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="padding:30px;background:rgb(0, 155, 255);">';
$body .= '<table role="presentation" style="width:100%;border-collapse:collapse;border:0;border-spacing:0;font-size:9px;font-family:Arial,sans-serif;">';
$body .= '<tr>';
$body .= '<td style="padding:0;width:50%;" align="left">';
$body .= '<p style="margin:0;font-size:14px;line-height:16px;font-family:Arial,sans-serif;color:#ffffff;">';
$body .= '&COPY; FullVitec 2021<br/><a href="https://www.fullvitec.com" style="color:#ffffff;text-decoration:underline;">Enviado desde www.fullvitec.com</a>';
$body .= '</p>';
$body .= '</td>';
$body .= '<td style="padding:0;width:50%;" align="right">';
$body .= '<table role="presentation" style="border-collapse:collapse;border:0;border-spacing:0;">';
$body .= '<tr>';										
$body .= '<td style="padding:0 0 0 10px;width:38px;">';
$body .= '<a href="http://www.facebook.com/" style="color:#ffffff;"><img src="https://assets.codepen.io/210284/fb_1.png" alt="Facebook" width="38" style="height:auto;display:block;border:0;" /></a>';
$body .= '</td>';
$body .= '</tr>';
$body .= '</table>';
$body .= '</td>';
$body .= '</tr>';
$body .= '</table>';
$body .= '</td>';
$body .= '</tr>';
$body .= '</table>';
$body .= '</td>';
$body .= '</tr>';
$body .= '</table>';
$body .= '</body>';
$body .= '</html>';

//echo $body;
?>